### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by scriptjumper** [shaeenk/nissan-fan-club-site#17]
The back image is not fitting too well with the site

**Comment by craigwheeler** [comment]
submitted a fix for the background image pr #20

**Comment by scriptjumper** [comment]
Hi @craigwheeler 

I wanted an image to replace the current one. The new image would have to fit in with the colours on the page

**Comment by scriptjumper** [comment]
The following pull request is what I was looking for.

**Pull request:**
https://github.com/shaeenk/nissanFanClub/pull/21

Thanks for the help @craigwheeler
