### ISSUE TITLE
Menu shows a horizontal scroll

### ISSUE THREAD

**Issue by scriptjumper** [shaeenk/nissan-fan-club-site#26]
Menu shows a horizontal scroll when a link was clicked 
![scroll-bar-after-click](https://user-images.githubusercontent.com/25608161/32718318-7290ff9a-c865-11e7-8965-3383e8931ee2.png)

**Comment by sol-idsnake** [comment]
@shaeenk  I can't reproduce this

**Comment by scriptjumper** [comment]
Issue was solved with the help of @dbeecham
